### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [trenta-io/rainier-UI-icons#30]
Hi there,
Just want to say that according to alternativeto.net Trenta OS is discontinued,
https://alternativeto.net/software/trenta-os/

Please Fix it

**Comment by KevDoy** [comment]
We'll get ahold of the folks at alternativeto.net and get that fixed. Closing the issue since it isn't related to the Rainier UI Icons repo.

Thank you
